POST http://localhost:2000/register/
Content-Type: application/json

{
  "user_id":8,
  "name":"indu",
  "username":"indu9999",
  "password":"888888",
  "role":"student",
  "course_id":2
}


####
POST http://localhost:2000/login/
Content-Type: application/json

{
  "username":"ravali9999",
  "password":"111111"
}

####visitor####
//(api-1)
GET http://localhost:2000/home/courses/2/

####
//(api-2)
GET http://localhost:2000/home/courses/


####User####
//(api-3)
GET http://localhost:2000/dashboard/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvaGl0OTk5OSIsImlhdCI6MTYzMDc3NzUyMH0.K0c4auvDfKIGRyfBvQv9TjkQr1vu33XBAyODoANfP1U

####
//(api-4)
GET http://localhost:2000/dashboard/2/subjects/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvaGl0OTk5OSIsImlhdCI6MTYzMDc3NzUyMH0.K0c4auvDfKIGRyfBvQv9TjkQr1vu33XBAyODoANfP1U

####
//(api-5)
GET http://localhost:2000/dashboard/2/subjects/3/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvaGl0OTk5OSIsImlhdCI6MTYzMDc3NzUyMH0.K0c4auvDfKIGRyfBvQv9TjkQr1vu33XBAyODoANfP1U

####
//(api-6)
GET http://localhost:2000/dashboard/2/subjects/3/6/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvaGl0OTk5OSIsImlhdCI6MTYzMDc3NzUyMH0.K0c4auvDfKIGRyfBvQv9TjkQr1vu33XBAyODoANfP1U

####
//(api-7)
GET http://localhost:2000/download_certificate
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvaGl0OTk5OSIsImlhdCI6MTYzMDc3NzUyMH0.K0c4auvDfKIGRyfBvQv9TjkQr1vu33XBAyODoANfP1U


####TUTOR####
//(api-8)
GET http://localhost:2000/learning_status/2/?status=IN%20PROGRESS
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmFsaTk5OTkiLCJyb2xlIjoidHV0b3IiLCJpYXQiOjE2MzEwMDk3MTN9.jLg3vLC6q-1YRVI5vwJeD70r5NCjs4L1s7GlcxuGsEk


####
//(api-9)
POST http://localhost:2000/materials/add-material/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmFsaTk5OTkiLCJyb2xlIjoidHV0b3IiLCJpYXQiOjE2MzEwMDk3MTN9.jLg3vLC6q-1YRVI5vwJeD70r5NCjs4L1s7GlcxuGsEk

{
    "material_id":11,
    "subject_id":3,
    "topic":"javascript-practice-questions",
    "material_content":"JavascriptPracticeQuestions.pdf"
}


####
//(api-10)
POST http://localhost:2000/materials/add-session/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmFsaTk5OTkiLCJyb2xlIjoidHV0b3IiLCJpYXQiOjE2MzEwMDk3MTN9.jLg3vLC6q-1YRVI5vwJeD70r5NCjs4L1s7GlcxuGsEk

{
    "subject_id":5,
    "course_id":2,
    "video":"More-NodeJs-Concepts-video-link",
    "subject_name":"Advansed-NodeJs"
}

####
//(api-11)
GET http://localhost:2000/courses/2/students/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmFsaTk5OTkiLCJyb2xlIjoidHV0b3IiLCJpYXQiOjE2MzEwMDk3MTN9.jLg3vLC6q-1YRVI5vwJeD70r5NCjs4L1s7GlcxuGsEk

####
//(api-12)
DELETE http://localhost:2000/delete-material/11/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmFsaTk5OTkiLCJyb2xlIjoidHV0b3IiLCJpYXQiOjE2MzEwMDk3MTN9.jLg3vLC6q-1YRVI5vwJeD70r5NCjs4L1s7GlcxuGsEk

